### ISSUE TITLE
Change optimizer to something faster

### ISSUE THREAD

**Issue by connormayer** [connormayer/maxent.ot#8]
Right now the package uses the `optim` function in R with `L-BFGS-B`, which allows boundary constraints. It's fairly slow for large inputs, and has a tendency to result in numeric overflow unless you're careful with weight bounds.

The `glmnet` package fits logistic regression models with boundary constraints. We should look into using this package.

**Comment by connormayer** [comment]
Could be issues with respect to normalization, however.

**Comment by adelrtan** [comment]
We're currently not using the `gr` argument of the `optim` function. 
Giving `optim` a function that enables it to analytically calculate the gradient would speed things up compared to having to numerically approximate the gradient.

**Comment by connormayer** [comment]
It's just the idea that it's doing conditional probabilities, which means we normalize over particular inputs rather than globally.

**Comment by connormayer** [comment]
Adding the `gr` argument is a great plan!

**Comment by connormayer** [comment]
Gradient has been added by @adelrtan, got about a 4x speed up on the case I tested.
